### ISSUE TITLE
Update for fields subset 

### ISSUE THREAD

**Issue by jaumard** [schultek/stormberry#19]
In my API I want to do a `PATCH` request. So I need to be able to do an update just for few fields.
For now the generate update method allow only the update all at once.

**Comment by schultek** [comment]
Can you specify? In the UpdateRequest, you can just specify a single field to update and there others are left untouched.

**Comment by jaumard** [comment]
Ho you're right I didn't test it and just by the look of the code I was thinking everything was override.  But I just tested and you're right only was it specified is changed. But that's trigger another problem, how can I set a field back to null ?

**Comment by jaumard** [comment]
And also foreign keys are still mandatory on the generated code: 
```
@MappableClass()
class SupplierUpdateRequest {
  SupplierUpdateRequest(
      {required this.id,
      required this.shopId,
      this.fullName,
      this.email,
      this.iban,
      this.accountName,
      this.phoneNumber,
      this.isEnabled,
      this.lastMod,
      this.added});
  int id;
  int shopId;
  String? fullName;
  String? email;
  String? iban;
  String? accountName;
  String? phoneNumber;
  bool? isEnabled;
  DateTime? lastMod;
  DateTime? added;
} 
```

**Comment by schultek** [comment]
> Ho you're right I didn't test it and just by the look of the code I was thinking everything was override.  But I just tested and you're right only was it specified is changed. But that's trigger another problem, how can I set a field back to null ?  

Oh right, I didn't thought of that. Ok thats a problem.

**Comment by schultek** [comment]
> And also foreign keys are still mandatory on the generated code: 
> ```
> @MappableClass()
> class SupplierUpdateRequest {
>   SupplierUpdateRequest(
>       {required this.id,
>       required this.shopId,
>       this.fullName,
>       this.email,
>       this.iban,
>       this.accountName,
>       this.phoneNumber,
>       this.isEnabled,
>       this.lastMod,
>       this.added});
>   int id;
>   int shopId;
>   String? fullName;
>   String? email;
>   String? iban;
>   String? accountName;
>   String? phoneNumber;
>   bool? isEnabled;
>   DateTime? lastMod;
>   DateTime? added;
> } 
> ```

That's a bug, what does the Supplier model and the Shop model look like?

**Comment by jaumard** [comment]
Look like this:
```

@Model(
  tableName: 'suppliers_supplier',
  insertRequestAnnotation: MappableClass(),
  updateRequestAnnotation: MappableClass(),
  views: [
    View('Complete', [Field.view('shop', as: 'Abstract')], MappableClass()),
  ],
)
abstract class Supplier {
  /// A unique identifier corresponding to this item.
  //@Column(indexType: IndexType.primaryKey)
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  Shop get shop;

  String get fullName;

  String get email;

  String get iban;

  String get accountName;

  String? get phoneNumber;

  //@Column(defaultValue: true)
  bool get isEnabled;

  DateTime get lastMod;

  DateTime get added;
}

@Model(
  tableName: 'contracts_shop',
  views: [
    View('Abstract', [Field.hidden('industryId')], MappableClass()),
    View('Full', [], MappableClass()),
  ],
)
abstract class Shop {
  /// A unique identifier corresponding to this item.
  @PrimaryKey()
  @AutoIncrement()
  int? id;

  String get name;

  int? get industryId;

  DateTime get added;
}

```

**Comment by schultek** [comment]
@jaumard 
I added a fix for the required foreign keys.

For setting columns to null through update requests please file a new issue.
This feature actually is really tricky. I haven't found a way to do it yet, since in sql there is no way smart to represent both 'keep this column untouched' and 'set this column to null' since we only have `null` as a value we can inject. We would need some extra value for each column (e.g. bool) to encode that information in sql.
