### ISSUE TITLE
Problem with encodings on emails

### ISSUE THREAD

**Issue by jaumard** [schultek/stormberry#20]
I have an email field but stormberry is replacing @ by @@ which make the email not usable ^^
![Simulator Screen Shot - iPhone 13 - 2022-08-24 at 12 08 45](https://user-images.githubusercontent.com/2970449/186392113-89031739-65c3-48a5-8512-25e0f10520ea.png)

**Comment by schultek** [comment]
This was done for this: https://pub.dev/documentation/postgres/latest/postgres/PostgreSQLConnection/query.html
and should be replaced by a single '@' by the postgres package. Not sure if thats a bug with the postgres package then. 
Can you test this by manually making some queries using the 'query()' method?

**Comment by jaumard** [comment]
@schultek this @param is use by `query` if you use the `substitutionValues` but here in your generated code you don't use them so it just keep your query as it is with 2 @. That make me think that we should use them as the Postgres package use the `substitutionValues` to prevent some SQL injection on them already so we don't have to do much

**Comment by tayormi** [comment]
I am having this issue as well. I'm not sure how to solve this.

**Comment by schultek** [comment]
Fixed in 0.9.2
