### ISSUE TITLE
Separate model class in different files ? 

### ISSUE THREAD

**Issue by CharlotteJu** [schultek/stormberry#39]
Hello,

Is it planned to be able to separate model classes in different files ?
The goal is to be able to have 1 class/file to find it more easily when you have a lot of different classes.

**Comment by schultek** [comment]
Yes I'm currently working on this.

**Comment by CharlotteJu** [comment]
Great ! Do you have any idea when this will be available?

**Comment by schultek** [comment]
Released in `v0.10.0`
