### ISSUE TITLE
[Issue] Can't generate schemes from many files

### ISSUE THREAD

**Issue by MindMayhem** [schultek/stormberry#4]
Hi, error described in header
When i was tried to generate scheme from two files in **build.yaml** - it's create only one table (for item1)
So, i tried to disable item1 and build another time, but scheme patcher just dropped 'item1' table and created new table for item2

At the current moment, I decided to remove any 'table dropping' code from source code (just as temporary solution) and generate new table for each item in builder.yaml - it works

Seems like patcher can't recognize multiple schemes, i think it's error and it should be fixed

![image](https://user-images.githubusercontent.com/39557395/171266821-8fc2951c-83e9-4cbe-8397-eedacdf9a862.png)

![image](https://user-images.githubusercontent.com/39557395/171267374-a430649c-7797-4255-bf1f-237e33f50020.png)

**Comment by schultek** [comment]
Added in version `0.7.0`
