### ISSUE TITLE
Error: `Unhandled Exception: PostgreSQLSeverity.error 42P01: relation "use_cases_id_seq" does not exist`

### ISSUE THREAD

**Issue by FMorschel** [schultek/stormberry#46]
Running my Flutter project and trying to insert a new row into my `use_cases` table throws this error:

`Unhandled Exception: PostgreSQLSeverity.error 42P01: relation "use_cases_id_seq" does not exist`

But when using pgAdmin4 I can easily do the same select it's trying to do (`SELECT nextval('use_cases_id_seq') as \"id\"`) and it runs perfectly. I'm trying to learn how to use the package. The connection is using the `postgres` user.

```dart
@Model()
abstract class UseCase {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get identifier;
  String get name;
  String get briefDescription;
  String get description;
  String get preCondition;
}
```

**Comment by schultek** [comment]
Mh I don't really have an idea for that. 

Can you zry removing the @AutoIncrement, migrating, adding it again, and migrating again?

**Comment by schultek** [comment]
@FMorschel I have changed how auto increment columns are handled in the newest version, maybe your issue is also solved by that.

**Comment by FMorschel** [comment]
Seems like it! Thanks! Although I still had a problem while trying to migrate, I had to manually drop the indexes and recreate them because it would tell me all the indexes already existed (even when I successfully migrated with no indexes). My indexes were unique, so that might have something to do with it, but now that I've dropped them, it worked!
