### ISSUE TITLE
Cant Update One nor Update Many

### ISSUE THREAD

**Issue by Rekshot21** [schultek/stormberry#48]
Im having this error when I try to update:  
"An exception occurred.
PostgreSQLException (PostgreSQLSeverity.error 42883: operator does not exist: integer = text Hint: No operator matches name and types of arguments. Explicit type conversion may need to be added.)"  
  
This is my call:  
![image](https://user-images.githubusercontent.com/62195132/217155348-552dc3c3-94e2-4e7d-8692-66f4de834dec.png)  
  
This is my model:  
![image](https://user-images.githubusercontent.com/62195132/217155441-e98a7e10-5e87-4b5e-989a-514e0e34594d.png)  
  
I did the migration 4 times already, I tried to workaround this by making a get, delete and insert, but I cant specify the Id in the insert either.  Am I doing something wrong?

**Comment by Rekshot21** [comment]
I didnt change any field from int to string and the migration was succesfull every time.

![image](https://user-images.githubusercontent.com/62195132/217300475-897f5e1b-aa36-47ca-ab0f-25cae6b881df.png)

Table:
![image](https://user-images.githubusercontent.com/62195132/217300160-fc5ae251-d64c-4280-a51a-b0ab2ffa55ec.png)

**Comment by schultek** [comment]
Ok I need to test this then. On what version are you?

**Comment by Rekshot21** [comment]
stormberry: ^0.10.0

Dart: 2.18.3

**Comment by Rekshot21** [comment]
@schultek  Hey I was testing this out, it seems the error is when postgres replaces the id parameter it adds the '  and thats why its failing. 

So this was the query that was been generated:    

UPDATE "users"
SET "name" = COALESCE(UPDATED."name"::text, "users"."name"), "age" = COALESCE(UPDATED."age"::int8, "users"."age")
FROM ( VALUES ( @0, @1, @2 ) )
AS UPDATED("id", "name", "age")
WHERE "users"."id" = UPDATED."id"
  
The query is okay but when postgress replaces the parameters the @0 goes from the intended int id (for example 1) to a string type (1 will turn into '1').   
  
If I use a String Id it works okay.  
  
Also if I have a field as bigint and postgress does the same thing (for example I try to set a 54 and postgres mades it a '54') it works alright and I have no errors.  
  
I hope being right and that this helps.    
  
Testing made for easier follow  up:    

Int Id Model  
´´´dart 
@Model()
abstract class User {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  int get businessId;

  String get userName;

  String? get email;

  String? get phone;

  String get password;

  String get role;
}
´´´
Generated Query:  
´´´
---
UPDATE "users"
SET "business_id" = COALESCE(UPDATED."business_id"::int8, "users"."business_id"), "user_name" = COALESCE(UPDATED."user_name"::text, "users"."user_name"), "email" = COALESCE(UPDATED."email"::text, "users"."email"), "phone" = COALESCE(UPDATED."phone"::text, "users"."phone"), "password" = COALESCE(UPDATED."password"::text, "users"."password"), "role" = COALESCE(UPDATED."role"::text, "users"."role")
FROM ( VALUES ( @0, @1, @2, @3, @4, @5, @6 ) )
AS UPDATED("id", "business_id", "user_name", "email", "phone", "password", "role")
WHERE "users"."id" = UPDATED."id"
´´´
The Query has the right syntax in PgAdmin4  
![image](https://user-images.githubusercontent.com/62195132/218929561-e435b211-4c34-4767-9569-49ad88c88415.png)

If I input the parameters manually:  
![image](https://user-images.githubusercontent.com/62195132/218930090-d3fb0605-da9d-4e84-a252-8b64c84345ac.png)  
It Updates no problem:  
![image](https://user-images.githubusercontent.com/62195132/218930142-5496c1c1-a258-408b-b738-1feb9aa7d289.png)
    
If I set the ID as a String manually I have the error above  
![image](https://user-images.githubusercontent.com/62195132/218930271-e752e827-4676-452b-ae71-48f041018654.png)
![image](https://user-images.githubusercontent.com/62195132/218930324-fc00e664-436e-42f3-88ae-4c6437e393bd.png)

It might be another thing but from I was testing this I what i found,

hope this helps

**Comment by schultek** [comment]
Thanks I think I know now how to fix it.

**Comment by schultek** [comment]
Should be fixed in v0.11.0

**Comment by mhmzdev** [comment]
FYI
I'm facing this issue in `0.12.1`

If I change the `id` to `int` manually it works

**Comment by schultek** [comment]
@mhmzdev Can you open a new issue for your problem?
