### ISSUE TITLE
Self-join relations

### ISSUE THREAD

**Issue by f3l1x98** [schultek/stormberry#49]
I am having the issue of trying to create a 1:1 relation between the same table.  

```dart
@Model()
abstract class Game {
  @PrimaryKey()
  @AutoIncrement()
  int get id;
  
  // [...]
  
  Game? get prequel;
  //Game? get sequel;  // GameA.sequel = GameB.prequel
}
```

This will generate a schema with two `prequelId`s (probably due to cyclic issues, because none are a List). If I also add the `sequel` it will result into three `prequelId`s and one `sequelId`.

Not sure, but perhaps this could be fixed by adding somekind of `Join` annotation (similar to NestJs Typeorm, Spring Boot JPA, ...) that allows specifying the join column/attribute:  
```dart
@Model()
abstract class Game {
  @PrimaryKey()
  @AutoIncrement()
  int get id;
  
  // [...]
  
  @Join('sequel')
  Game? get prequel;
  @Join('prequel')
  Game? get sequel;
}
```

This annotation could also be expanded to allow joins on non-primary key columns.

**Comment by schultek** [comment]
I have never considered self-joins. I will try to add support for it.

**Comment by schultek** [comment]
Self-Joins as well as a new `@BindTo` annotation are added in the [`v0.12.0` release](https://github.com/schultek/stormberry/releases/tag/v0.12.0).
