### ISSUE TITLE
Using other Postgre datatypes 

### ISSUE THREAD

**Issue by danielreghin** [schultek/stormberry#66]
Is there a way of using other postgre data types than the defaults that comes from using (String, bool, int) dart data types?
For exemple I want to use Date instead of timestamp. Varchar(255) instead text and so on. 
I tried to use CustomDataTypes but wihout success.

class DateConverter extends TypeConverter<DateTime> {
  const DateConverter() : super('date');
  ...
}

@UseConverter(DateConverter())
  DateTime get dtOpen

**Comment by schultek** [comment]
I would have suggested the way you wrote, so I don't know right now why it doesnt work. I have to investigate.

**Comment by danielreghin** [comment]
HI. 
I made it work somehow. Did it again, ran build_runner and it worked. I must have made a mistake at the first time.
Not an issue anymore. Thanks.

**Comment by schultek** [comment]
Cool thanks.
