### ISSUE TITLE
Default view is missing

### ISSUE THREAD

**Issue by schultek** [schultek/stormberry#7]
No default view is generated for a model without views.

**Comment by schultek** [comment]
We still need a view to resolve any relations to other tables

**Comment by jaumard** [comment]
Feels weird to never query the real data and to create a view that will be always the same as the table itself. 
Can't we support directly on the field something like `@Field.view(as: 'ShopAbstract')` if we want it specify a specific view and if we don't want it should take the other table fully too.

**Comment by schultek** [comment]
To be clear it would feel like querying the table itself, but internally it is implemented as a view.

**Comment by jaumard** [comment]
I understood but it means that if you check the database schema you'll have a table and a view that are exactly the same right? So making the database doing extra work for nothing in the end. That's what I want to avoid. Because for sure for the user of the ORM it will be transparent.

**Comment by schultek** [comment]
Not the same. If your model has a relation to another model, the table would just have a column with the foreign key, but the view would have the resolved model (joined table).

**Comment by schultek** [comment]
Fixed in 1572cfc
