### ISSUE TITLE
I can't add enum

### ISSUE THREAD

**Issue by n1kStas** [schultek/stormberry#73]
I'm trying to add an enum but I get an error

```
import 'package:stormberry/stormberry.dart';
part 'item.schema.dart';

enum ItemType {
  car, moto
}

@Model()
abstract class Item {
  @PrimaryKey()
  @AutoIncrement()
  int get id;
  @UseConverter(EnumTypeConverter(ItemType.values))
  ItemType get itemType;
  String get name;
}
```
Failed to build database schema:

The following field has an unsupported type:
  - Field "ItemType itemType" in class "abstract class Item"
Either change the type to a supported column type, make the class a [Model] or use a custom [TypeConverter] with [@UseConverter].

**Comment by schultek** [comment]
Should be:
```dart
@UseConverter(EnumTypeConverter<ItemType>(ItemType.values))
ItemType get itemType;
```
