### ISSUE TITLE
How to generate toJson, fromJson methods for models in last versions of stormberry package?

### ISSUE THREAD

**Issue by playbott** [schultek/stormberry#74]
I am using the ***stormberry v0.14.0***. As I know, there should be annotations for JSON serialization. 
I found [code](https://github.com/schultek/stormberry/commit/36fb7fb8c1981c202799940e63f852901d440df3) with using views in *@Model* annotation, but it seems View class doesn't exist.
Are there any ways to generate toJson, fromJson methods?

**Comment by schultek** [comment]
See the 'meta' property on the @Model annotation

**Comment by playbott** [comment]
> See the 'meta' property on the @model annotation

Hi! Thank you! I realized how to use it.
